spring:
  application:
    name: Department Service

application:
  welcomeMessage: welcome,Baljeet Malik, Hope you are going well

server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8061/eureka}
  instance:
    preferIpAddress: true
    metadataMap: 
      instanceId: ${spring.application.name}:${random.int}
