spring:
  application:
    name: Employee Service
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8061/eureka}
  instance:
    preferIpAddress: true
    metadataMap: 
      instanceId: ${spring.application.name}:${random.int}